homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"
homebrew_brewfile_dir: '~'
homebrew_cask_accept_external_apps: false
homebrew_cask_appdir: /Applications
homebrew_casks: []
homebrew_clear_cache: false
homebrew_folders_additional: []
homebrew_install_path: "{{ homebrew_prefix }}{{ '/Homebrew' if ansible_machine != 'arm64' }}"
homebrew_installed_packages: []
homebrew_repo: https://github.com/Homebrew/brew
homebrew_taps: []
homebrew_uninstalled_casks: []
homebrew_uninstalled_packages: []
homebrew_upgrade_all_packages: false
homebrew_use_brewfile: false
homebrew_folders_base:
- Cellar
- Frameworks
- Caskroom
- bin
- etc
- include
- lib
- opt
- sbin
- share
- share/zsh
- share/zsh/site-functions
- var
