# yaml-language-server $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json

- name: "Hard Drives on Desktop"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: "{{ Defaults_Desktop_ShowHardDrives }}"
    state: present
  notify: Finder Restart

- name: "External Hard Drives on Desktop"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: "{{ Defaults_Desktop_ShowExternalHardDrives }}"
    state: present
  notify: Finder Restart

- name: "Removable Media on Desktop"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: "{{ Defaults_Desktop_ShowRemovableMedia }}"
    state: present
  notify: Finder Restart

- name: "Mounted Servers on Desktop"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: "{{ Defaults_Desktop_ShowMountedServers }}"
    state: present
  notify: Finder Restart

- name: "Desktop Icons"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: CreateDesktop
    type: bool
    value: "{{ Defaults_Desktop_ShowIcons }}"
    state: present
  notify: Finder Restart
