# yaml-language-server $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json

- name: "[DOCK] Position"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: "{{ Defaults.Dock.Position }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Auto-hide"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "{{ Defaults.Dock.Autohide.Enabled }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Auto-hide Delay"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: "{{ Defaults.Dock.Autohide.Delay }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Auto-hide Animation Duration"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: "{{ Defaults.Dock.Autohide.AnimationDuration }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Icon size"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: "{{ Defaults.Dock.Icons.Size }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Magnification"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: "{{ Defaults.Dock.Icons.Magnification }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Magnification size"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: float
    value: "{{ Defaults.Dock.Icons.MagnificationSize }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Show Recents"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: "{{ Defaults.Dock.ShowRecents }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Show hidden"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: "{{ Defaults.Dock.ShowHidden }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Pinning"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: pinning
    type: string
    value: "{{ Defaults.Dock.Pinning }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Minimize to application"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: "{{ Defaults.Dock.MinimizeToApplication }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] No bouncing"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: no-bouncing
    type: bool
    value: "{{ Defaults.Dock.NoBouncing }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Launch animation"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: "{{ Defaults.Dock.Animations.Launch }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Minimize effect"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: "{{ Defaults.Dock.Animations.MinimizeEffect }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Scroll to open"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: scroll-to-open
    type: bool
    value: "{{ Defaults.Dock.ScrollToOpen }}"
    state: present
  notify: Dock Restart

- name: "[DOCK] Show App Expose Gesture"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: showAppExposeGestureEnabled
    type: bool
    value: "{{ Defaults.Dock.ShowAppExposeGestureEnabled }}"
    state: present
  notify: Dock Restart

# # DEFAULTS
# # defaults write com.apple.dock magnification -bool true
# - name: "[macdock_defaults] System Preferences > Dock > Magnification: {{ macdock_magnify }}"
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: magnification
#     type: bool
#     value: "{{ macdock_magnify }}"
#     state: present
#   notify: Restart Dock

# # defaults write com.apple.dock mineffect -string "scale"
# - name: "[macdock_defaults] System Preferences > Dock > Minimize windows using: Scale effect"
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: mineffect
#     type: string
#     value: 'scale'
#     state: present
#   notify: Restart Dock

# # defaults write com.apple.dock minimize-to-application -bool true
# - name: "[macdock_defaults] System Preferences > Dock > Minimize windows into application icon"
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: minimize-to-application
#     type: bool
#     value: true
#     state: present
#   notify: Restart Dock

# # defaults write com.apple.dock autohide -bool false
# - name: "[macdock_defaults] System Preferences > Dock > Automatically hide and show the Dock: {{ macdock_hide }}"
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: autohide
#     type: bool
#     value: "{{ macdock_hide }}"
#     state: present
#   notify: Restart Dock

# # defaults write com.apple.dock autohide-time-modifier -float 0.5
# - name: "[macdock_defaults] System Preferences > Dock > Automatically hide and show the Dock (duration - 0.5)"
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: autohide-time-modifier
#     type: float
#     value: 0.5
#     state: present
#   notify: Restart Dock

# # defaults write com.apple.dock autohide-delay -float 0
# - name: "[macdock_defaults] System Preferences > Dock > Automatically hide and show the Dock (delay - 0)"
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: autohide-delay
#     type: float
#     value: 0
#     state: present
#   notify: Restart Dock

# # defaults write com.apple.dock show-process-indicators -bool true
# - name: "[macdock_defaults] System Preferences > Dock > Show indicators for open applications"
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: show-process-indicators
#     type: bool
#     value: true
#     state: present
#   notify: Restart Dock

# # defaults write com.apple.dock expose-animation-duration -float 0.12
# - name: "[macdock_defaults] Speed up the Mission Control animations"
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: expose-animation-duration
#     type: float
#     value: 0.12
#     state: present
#   notify: Restart Dock
