# yaml-language-server $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json

- name: "Position"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: "{{ Defaults_Dock_Position }}"
    state: present
  notify: Dock Restart

- name: "Auto-hide"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "{{ Defaults_Dock_Autohide_Enabled }}"
    state: present
  notify: Dock Restart

- name: "Auto-hide Delay"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: "{{ Defaults_Dock_Autohide_Delay }}"
    state: present
  notify: Dock Restart

- name: "Auto-hide Animation Duration"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: "{{ Defaults_Dock_Autohide_AnimationDuration }}"
    state: present
  notify: Dock Restart

- name: "Icon size"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: "{{ Defaults_Dock_Icons_Size }}"
    state: present
  notify: Dock Restart

- name: "Magnification"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: "{{ Defaults_Dock_Icons_Magnification }}"
    state: present
  notify: Dock Restart

- name: "Magnification size"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: float
    value: "{{ Defaults_Dock_Icons_MagnificationSize }}"
    state: present
  notify: Dock Restart

- name: "Show Recents"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: "{{ Defaults_Dock_ShowRecents }}"
    state: present
  notify: Dock Restart

- name: "Show hidden"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: "{{ Defaults_Dock_ShowHidden }}"
    state: present
  notify: Dock Restart

- name: "Pinning"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: pinning
    type: string
    value: "{{ Defaults_Dock_Pinning }}"
    state: present
  notify: Dock Restart

- name: "Minimize to application"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: "{{ Defaults_Dock_MinimizeToApplication }}"
    state: present
  notify: Dock Restart

- name: "No bouncing"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: no-bouncing
    type: bool
    value: "{{ Defaults_Dock_NoBouncing }}"
    state: present
  notify: Dock Restart

- name: "Launch animation"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: "{{ Defaults_Dock_Animations_Launch }}"
    state: present
  notify: Dock Restart

- name: "Minimize effect"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: "{{ Defaults_Dock_Animations_MinimizeEffect }}"
    state: present
  notify: Dock Restart

- name: "Scroll to open"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: scroll-to-open
    type: bool
    value: "{{ Defaults_Dock_ScrollToOpen }}"
    state: present
  notify: Dock Restart

- name: "Show App Expose Gesture"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: showAppExposeGestureEnabled
    type: bool
    value: "{{ Defaults_Dock_ShowAppExposeGestureEnabled }}"
    state: present
  notify: Dock Restart

- name: "Show indicators for open applications"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: "{{ Defaults_Dock_ShowIndicators }}"
    state: present
  notify: Dock Restart

- name: "Speed up the Mission Control animations"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: "{{ Defaults_Dock_Animations_ExposeDuration }}"
    state: present
  notify: Dock Restart
