# yaml-language-server $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json

Defaults:
  Dock:
    ScrollToOpen: true
    ShowAppExposeGestureEnabled: false
    ShowHidden: true
    Pinning: middle
    MinimizeToApplication: true
    NoBouncing: false
    Animations:
      Launch: true
      MinimizeEffect: suck
    Autohide:
      Enabled: true
      AnimationDuration: 0.25
      Delay: 0.1
    Icons:
      Size: 42
      Magnification: true
      MagnificationSize: 44
    Position: left
    ShowRecents: false
