# yaml-language-server $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json
- name: "Show file extensions"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllExtensions
    type: bool
    value: "{{ Defaults_Finder_ShowFileExtensions }}"
    state: present
  notify: Finder Restart

- name: "Show hidden files"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: string
    value: "{{ Defaults_Finder_ShowHiddenFiles }}"
    state: present
  notify: Finder Restart

- name: "Show path bar"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: "{{ Defaults_Finder_ShowPathBar }}"
    state: present
  notify: Finder Restart

- name: "Set preferred view style"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "{{ Defaults_Finder_PreferredViewStyle }}"
    state: present
  notify: Finder Restart

- name: "Show status bar"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: "{{ Defaults_Finder_ShowStatusBar }}"
    state: present
  notify: Finder Restart

- name: "Set search scope"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "{{ Defaults_Finder_SearchScope }}"
    state: present
  notify: Finder Restart

- name: "Remove items from trash after 30 days"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXRemoveOldTrashItems
    type: bool
    value: "{{ Defaults_Finder_RemoveOldTrash }}"
    state: present
  notify: Finder Restart

- name: "Change extension warning"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: "{{ Defaults_Finder_ChangeExtensionWarning }}"
    state: present
  notify: Finder Restart

#- name: "Titlebar icon"
#  community.general.osx_defaults:
#    domain: com.apple.universalaccess
#    key: showWindowTitlebarIcons
#    type: bool
#    value: "{{ Defaults_Finder_TitlebarIcon }}"
#    state: present
#  notify: Finder Restart

- name: "Sidebar icon size"
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: "{{ Defaults_Finder_SidebarIconSize }}"
    state: present
  notify: Finder Restart
